version: '3.4'

services:
  shippy-service-consignment:
    container_name: "shippy"
    image: shippy_i
    build: .
    security_opt:
      - seccomp:unconfined
    #entrypoint: dlv debug /workspaces/shippy-service-consignment -l 0.0.0.0:2345 --headless=true --log=true -- server
    entrypoint: dlv debug --listen=:2345 --headless --api-version=2 --accept-multiclient --log=true
    #volumes:
    #  - .:/opt/go/src/local/myorg/myapp
    ports:
      - "2345:2345"
      - "50051:50051"
